version: "3.8"

services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    container_name: chemo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chemo_db
      MYSQL_USER: chemo_user
      MYSQL_PASSWORD: chemo_pass
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - chemo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    container_name: chemo-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://chemo_user:chemo_pass@mysql:3306/chemo_db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - PORT=5000
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - chemo-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    container_name: chemo-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost/api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - chemo-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

  # Development services (optional)
  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    platform: linux/arm64/v8
    container_name: chemo-backend-dev
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://chemo_user:chemo_pass@mysql:3306/chemo_db
      - JWT_SECRET=dev-jwt-secret
      - PORT=5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - chemo-network
    profiles:
      - dev
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  frontend-dev:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    platform: linux/arm64/v8
    container_name: chemo-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-dev
    networks:
      - chemo-network
    profiles:
      - dev
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

volumes:
  mysql_data:
    driver: local

networks:
  chemo-network:
    driver: bridge 